//alerts
export const CREATE_ALERT_SUCESS = 'CREATE_ALERT_SUCESS';
export const CREATE_ALERT_ERROR = 'CREATE_ALERT_ERROR';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';
//auth
export const GET_USER = 'GET_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_PERMISIONS = 'LOGIN_PERMISIONS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const RETRIEVE_TOKEN = 'RETRIEVE_TOKEN';
export const RETRIEVE_USER = 'RETRIEVE_USER';
export const NOT_LOADING = 'NOT_LOADING';
export const FORGET_PASWORD_SUCCESS = 'FORGET_PASWORD_SUCCESS';
export const FORGET_PASWORD_ERROR = 'FORGET_PASWORD_ERROR';
export const CLEAR = 'CLEAR';

//profile
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

//account
export const RETRIEVE_SELECTED_ACCOUNT = 'RETRIEVE_SELECTED_ACCOUNT';
export const RETRIEVE_SELECTED_FILIAL = 'RETRIEVE_SELECTED_FILIAL';
export const TOOGLE_ACCOUNT_SUCCESS = 'TOOGLE_ACCOUNT_SUCCESS';
export const TOOGLE_ACCOUNT_ERROR = 'TOOGLE_ACCOUNT_ERROR';
export const TOOGLE_ACCOUNT_MESSAGE = 'TOOGLE_ACCOUNT_MESSAGE';
//entrances
export const LOAD_ENTRANCES_SUCESS = 'LOAD_ENTRANCES_SUCESS';
export const LOAD_ENTRANCES_ERROR = 'LOAD_ENTRANCES_ERROR';
export const LOAD_ENTRANCES_MONTH_SUCESS = 'LOAD_ENTRANCES_MONTH_SUCESS';
export const LOAD_ENTRANCES_MONTH_ERROR = 'LOAD_ENTRANCES_MONTH_ERROR';
export const LOAD_ENTRANCES_WEEK_SUCESS = 'LOAD_ENTRANCES_WEEK_SUCESS';
export const LOAD_ENTRANCES_WEEK_ERROR = 'LOAD_ENTRANCES_WEEK_ERROR';
export const CLEAR_ENTRANCES = 'CLEAR_ENTRANCES';
//incidents
export const LOAD_INCIDENTS_SUCESS = 'LOAD_INCIDENTS_SUCESS';
export const LOAD_INCIDENTS_ERROR = 'LOAD_INCIDENTS_ERROR';
export const CREATE_INCIDENT_SUCCESS = 'CREATE_INCIDENT_SUCCESS';
export const CREATE_INCIDENT_ERROR = 'CREATE_INCIDENT_ERROR';
export const CLEAR_INCIDENT_ERRORS = 'CLEAR_INCIDENT_ERRORS';
export const SHOW_INCIDENT_SUCCESS = 'SHOW_INCIDENT_SUCCESS';
export const SHOW_INCIDENT_ERROR = 'SHOW_INCIDENT_ERROR';
export const UPDATE_INCIDENT_SUCCESS = 'UPDATE_INCIDENT_SUCCESS';
export const UPDATE_INCIDENT_ERROR = 'UPDATE_INCIDENT_ERROR';
export const CREATE_COMMENT_SUCESS = 'CREATE_COMMENT_SUCESS';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';
export const DELETE_COMMENT_SUCESS = 'DELETE_COMMENT_SUCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';
export const CLEAR_INCIDENTS = 'CLEAR_INCIDENTS';

//pets
export const LOAD_PETS_SUCESS = 'LOAD_PETS_SUCESS';
export const LOAD_PETS_ERROR = 'LOAD_PETS_ERROR';
export const CREATE_PET_SUCCESS = 'CREATE_PET_SUCCESS';
export const CREATE_PET_ERROR = 'CREATE_PET_ERROR';
export const CLEAR_PET_ERRORS = 'CLEAR_PET_ERRORS';
export const UPDATE_PET_SUCCESS = 'UPDATE_PET_SUCCESS';
export const UPDATE_PET_ERROR = 'UPDATE_PET_ERROR';
export const CREATE_ALERT_PET_SUCESS = 'CREATE_ALERT_PET_SUCESS';
export const CREATE_ALERT_PET_ERROR = 'CREATE_ALERT_PET_ERROR';
export const DELETE_PET_SUCCESS = 'DELETE_PET_SUCCESS';
export const DELETE_PET_ERROR = 'DELETE_PET_ERROR';
//bookings
export const LOAD_BOOKINGS_SUCCESS = 'LOAD_BOOKINGS_SUCCESS';
export const LOAD_BOOKINGS_ERROR = 'LOAD_BOOKINGS_ERROR';
export const LOAD_BOOKINGS_AREA_SUCESS = 'LOAD_BOOKINGS_AREA_SUCESS';
export const LOAD_BOOKINGS_AREA_ERROR = 'LOAD_BOOKINGS_AREA_ERROR';
export const LOAD_BOOKABLE_AREAS_SUCCESS = 'LOAD_BOOKABLE_AREAS_SUCCESS';
export const LOAD_BOOKABLE_AREAS_ERROR = 'LOAD_BOOKABLE_AREAS_ERROR';
export const LOAD_BOOKABLE_ALL_AREAS_SUCCESS =
  'LOAD_BOOKABLE_ALL_AREAS_SUCCESS';
export const LOAD_BOOKABLE_ALL_AREAS_ERROR = 'LOAD_BOOKABLE_ALL_AREAS_ERROR';
export const GENERATE_RANGE_HOURS = 'GENERATE_RANGE_HOURS';
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_ERROR = 'CREATE_BOOKING_ERROR';
export const SHOW_BOOKING_SUCESS = 'SHOW_BOOKING_SUCESS';
export const SHOW_BOOKING_ERROR = 'SHOW_BOOKING_ERROR';
export const REMOVE_GUEST_SUCCESS = 'REMOVE_GUEST_SUCCESS';
export const REMOVE_GUEST_ERROR = 'REMOVE_GUEST_ERROR';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_ERROR = 'UPDATE_BOOKING_ERROR';
export const UPDATE_GUEST_LIST = 'UPDATE_GUEST_LIST';
export const DELETE_SUCCESS_LIST = 'DELETE_SUCCESS_LIST';
export const LOAD_HISTORY_SUCCESS = 'LOAD_HISTORY_SUCCESS';
export const LOAD_HISTORY_ERROR = 'LOAD_HISTORY_ERROR';
export const CANCEL_BOOKING_SUCESS = 'CANCEL_BOOKING_SUCESS';
export const CANCEL_BOOKING_ERROR = 'CANCEL_BOOKING_ERROR';
export const CLEAR_BOOKING_ERRORS = 'CLEAR_BOOKING_ERRORS';
export const CLEAR_BOOKING = 'CLEAR_BOOKING';
//contacts
export const LOAD_CONTACT_SUCCESS = 'LOAD_CONTACT_SUCCESS';
export const LOAD_CONTACT_ERROR = 'LOAD_CONTACT_ERROR';

//owners
export const LOAD_OWNERS_SUCCESS = 'LOAD_OWNERS_SUCCESS';
export const LOAD_OWNERS_ERROR = 'LOAD_OWNERS_ERROR';
export const CLEAR_OWNERS = 'CLEAR_OWNERS';
export const CREATE_OWNERS_SUCCESS = 'CREATE_OWNERS_SUCCESS';
export const CREATE_OWNERS_ERROR = 'CREATE_OWNERS_ERROR';
export const CLEAR_OWNERS_ERRORS = 'CLEAR_OWNERS_ERRORS';

//tenants
export const LOAD_TENANTS_SUCCESS = 'LOAD_TENANTS_SUCCESS';
export const LOAD_TENANTS_ERROR = 'LOAD_TENANTS_ERROR';
export const CREATE_TENANTS_SUCCESS = 'CREATE_TENANTS_SUCCESS';
export const CREATE_TENANTS_ERROR = 'CREATE_TENANTS_ERROR';
export const CLEAR_TENANTS_ERRORS = 'CLEAR_TENANTS_ERRORS';
export const UPDATE_TENANTS_SUCCESS = 'UPDATE_TENANTS_SUCCESS';
export const UPDATE_TENANTS_ERROR = 'UPDATE_TENANTS_ERROR';
export const DELETE_TENANTS_SUCCESS = 'DELETE_TENANTS_SUCCESS';
export const DELETE_TENANTS_ERROR = 'DELETE_TENANTS_ERROR';
export const CLEAR_TENANTS = 'CLEAR_TENANTS';

//vehicles
export const LOAD_VEHICLES_SUCCESS = 'LOAD_VEHICLES_SUCCESS';
export const LOAD_VEHICLES_ERROR = 'LOAD_VEHICLES_ERROR';
export const CREATE_VEHICLES_SUCCESS = 'CREATE_VEHICLES_SUCCESS';
export const CREATE_VEHICLES_ERROR = 'CREATE_VEHICLES_ERROR';
export const UPDATE_VEHICLES_SUCCESS = 'UPDATE_VEHICLES_SUCCESS';
export const UPDATE_VEHICLES_ERROR = 'UPDATE_VEHICLES_ERROR';
export const DELETE_VEHICLES_SUCCESS = 'DELETE_VEHICLES_SUCCESS';
export const DELETE_VEHICLES_ERROR = 'DELETE_VEHICLES_ERROR';
export const CLEAR_VEHICLES = 'CLEAR_VEHICLES';
//letters
export const LOAD_LETTERS_SUCCESS = 'LOAD_LETTERS_SUCCESS';
export const LOAD_LETTERS_ERROR = 'LOAD_LETTERS_ERROR';
export const LOAD_LETTER_SUCCESS = 'LOAD_LETTER_SUCCESS';
export const LOAD_LETTER_ERROR = 'LOAD_LETTER_ERROR';
export const LOAD_ADMINS_SUCCESS = 'LOAD_ADMINS_SUCCESS';
export const LOAD_ADMINS_ERROR = 'LOAD_ADMINS_ERROR';
export const LOAD_LETTERS_SENT_SUCCESS = 'LOAD_LETTERS_SENT_SUCCESS';
export const LOAD_MESSAGES_ERROR = 'LOAD_MESSAGES_ERROR';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_LETTERS_SENT_ERROR = 'LOAD_LETTERS_SENT_ERROR';
export const CREATE_LETTERS_SUCCESS = 'CREATE_LETTERS_SUCCESS';
export const CREATE_LETTERS_ERROR = 'CREATE_LETTERS_ERROR';
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS';
export const CREATE_REPLY_ERROR = 'CREATE_REPLY_ERROR';
export const DELETE_LETTERS_SUCCESS = 'DELETE_LETTERS_SUCCESS';
export const DELETE_LETTERS_ERROR = 'DELETE_LETTERS_ERROR';
export const CLEAR_LETTERS = 'CLEAR_LETTERS';
export const CLEAR_LETTERS_OPTIONS = 'CLEAR_LETTERS_OPTIONS';

//autorizations
export const LOAD_AUTORIZATIONS_SUCCESS = 'LOAD_AUTORIZATIONS_SUCCESS';
export const LOAD_AUTORIZATIONS_ERRORS = 'LOAD_AUTORIZATIONS_ERRORS';
export const LOAD_SUBSIDIARY_SUCCESS = 'LOAD_SUBSIDIARY_SUCCESS';
export const SEND_AUTORIZATIONS_QR_SUCCESS = 'SEND_AUTORIZATIONS_QR_SUCCESS';
export const SEND_AUTORIZATIONS_QR_ERRORS = 'SEND_AUTORIZATIONS_QR_ERRORS';
export const LOAD_SUBSIDIARY_ERROR = 'LOAD_SUBSIDIARY_ERROR';
export const LOAD_OLD_AUTORIZATIONS_SUCCESS = 'LOAD_OLD_AUTORIZATIONS_SUCCESS';
export const LOAD_OLD_AUTORIZATIONS_ERRORS = 'LOAD_OLD_AUTORIZATIONS_ERRORS';
export const CREATE_AUTORIZATIONS_SUCCESS = 'CREATE_AUTORIZATIONS_SUCCESS';
export const CREATE_AUTORIZATIONS_ERROR = 'CREATE_AUTORIZATIONS_ERROR';
export const UPDATE_AUTORIZATIONS_SUCCESS = 'UPDATE_AUTORIZATIONS_SUCCESS';
export const UPDATE_AUTORIZATIONS_ERROR = 'UPDATE_AUTORIZATIONS_ERROR';
export const DELETE_AUTORIZATIONS_SUCCESS = 'DELETE_AUTORIZATIONS_SUCCESS';
export const DELETE_AUTORIZATIONS_ERROR = 'DELETE_AUTORIZATIONS_ERROR';
export const CLEAR_AUTORIZATIONS = 'CLEAR_AUTORIZATIONS';

//votings
export const LOAD_VOTINGS_SUCCESS = 'LOAD_VOTINGS_SUCCESS';
export const LOAD_VOTINGS_ERRORS = 'LOAD_VOTINGS_ERRORS';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_ERROR = 'LOAD_QUESTIONS_ERROR';
export const LOAD_RESULTS_SUCCESS = 'LOAD_RESULTS_SUCCESS';
export const LOAD_RESULTS_ERROR = 'LOAD_RESULTS_ERROR';
export const LOAD_CHARTS_SUCCESS = 'LOAD_CHARTS_SUCCESS';
export const LOAD_CHARTS_ERROR = 'LOAD_CHARTS_ERROR';
export const CREATE_VOTINGS_SUCCESS = 'CREATE_VOTINGS_SUCCESS';
export const CREATE_VOTINGS_ERROR = 'CREATE_VOTINGS_ERROR';
export const CLEAR_VOTINGS = 'CLEAR_VOTINGS';
export const CLEAR_VOTINGS_ERROR = 'CLEAR_VOTINGS_ERROR';
export const CREATE_ANSWERS_SUCCESS = 'CREATE_ANSWERS_SUCCESS';
export const CREATE_ANSWERS_ERROR = 'CREATE_ANSWERS_ERROR';
//documents
export const LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS';
export const LOAD_DOCUMENTS_ERRORS = 'LOAD_DOCUMENTS_ERRORS';
export const LOAD_DOCUMENTS_CATEGORIES_SUCCESS =
  'LOAD_DOCUMENTS_CATEGORIES_SUCCESS';
export const LOAD_DOCUMENTS_CATEGORIES_ERROR =
  'LOAD_DOCUMENTS_CATEGORIES_ERROR';

export const LOAD_LINKS_SUCCESS = 'LOAD_LINKS_SUCCESS';
export const LOAD_LINKS_ERROR = 'LOAD_LINKS_ERROR';
export const DOCUMENTS_CLEAR = 'DOCUMENTS_CLEAR';

//notifications
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';
export const SUBSCRIPTION_ERROR = 'SUBSCRIPTION_ERROR';
export const UNSUBSCRIPTION_SUCCESS = 'UNSUBSCRIPTION_SUCCESS';
export const UNSUBSCRIPTION_ERROR = 'UNSUBSCRIPTION_ERROR';
export const LOAD_SUBSCRIPTION_SUCCESS = 'LOAD_SUBSCRIPTION_SUCCESS';
export const LOAD_SUBSCRIPTION_ERROR = 'LOAD_SUBSCRIPTION_ERROR';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

//codes
export const CREATE_CODE_SUCCESS = 'CREATE_CODE_SUCCESS';
export const CREATE_CODE_ERROR = 'CREATE_CODE_ERROR';
export const CLEAR_CODE_MESSAGES = 'CLEAR_CODE_MESSAGES';
